[participants] Use pattern packages instead of patterns
MeeGoIntegration/boss-standard-workflow pull request #46
Opened 2022-11-04 15:11 UTC by martyone

2022-11-07 20:04 UTC, keto requested changes

2022-11-08 07:48 UTC, martyone commented on participants/select_test_packages.py
> +                    selected.update({required: []})
Thinking what to write in the comment, I checked it once again how the list is used. Remember we found it ignored on qa-dister side. But now I found it is used also by the filter_test_packages participant and it finally makes a sense to me why the original code assigned Provides of the pattern there :) Fixed.

2022-11-08 08:21 UTC, martyone commented on participants/select_test_packages.py
>      qa.test_patterns(dict):
Done

2022-11-08 17:38 UTC, keto approved these changes
LGTM

2022-11-08 17:43 UTC, merged